### ISSUE TITLE
Error in installation step

### ISSUE THREAD

**Issue by thiphan94** [hujiecpp/ISTR#24]
Hello, 

Thank you very much for sharing the code for the model,

I'm trying to follow the installation guide.  However, when I run the command `python setup.py build develop`, I get the error below:

```bash
Traceback (most recent call last):
  File "setup.py", line 174, in get_model_zoo_configs
    os.symlink(source_configs_dir, destination)
FileExistsError: [Errno 17] File exists: '/home/thi/ISTR/configs' -> '/home/thi/ISTR/detectron2/model_zoo/configs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    package_data={"detectron2.model_zoo": get_model_zoo_configs()},
  File "setup.py", line 177, in get_model_zoo_configs
    shutil.copytree(source_configs_dir, destination)
  File "/home/thi/anaconda3/envs/ISTR/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/thi/ISTR/configs'

```

Can you help me fix this, please? Thank you very much!

**Comment by hujiecpp** [comment]
Pls check if the folder `./detectron2/model_zoo/` exists.

**Comment by codylcs** [comment]
安装步骤最好说明下，先安装detectron2,因为安装步骤没写，默认./detectron2/model_zoo/也没有configs文件夹，还有模型路径不支持”\“,只认"/“,模型的命令也是需要严格对上的，我后面贴下，希望帮助到其他人吧
你们的工作很辛苦，这些东西如果不做好，会影响你们的start数量的
`python demo/demo.py --config-file projects/ISTR/configs/ISTR-PCA-R50-3x.yaml --input F:/vv/vv.jpg --output ./output --confidence-threshold 0.4 --opts MODEL.WEIGHTS E:/pycharmpro/Myseg/ISTR/output-ISTR-PCA-R50/model_final_istr_pca_r50.pth`

**Comment by veryverybigdragon** [comment]
用這串指令(python setup.py build develop)時產生以下問題，請問如何解決
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    package_data={"detectron2.model_zoo": get_model_zoo_configs()},
  File "setup.py", line 177, in get_model_zoo_configs
    shutil.copytree(source_configs_dir, destination)
  File "C:\Users\USER\anaconda3\envs\ISTR\lib\shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'D:\\instance segmentation\\ISTR\\configs'
